import './App.css';
const CHANNELS = 4;
const ROWS = 16;
var tune = {
  channels: [
    {
      id: 0,
      rows: [
        {
          id: 0,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 1,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 2,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 3,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 4,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 5,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 6,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 7,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 8,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 9,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 10,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 11,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 12,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 13,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 14,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 15,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
      ],
    },
    {
      id: 1,
      rows: [
        {
          id: 0,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 1,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 2,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 3,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 4,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 5,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 6,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 7,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 8,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 9,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 10,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 11,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 12,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 13,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 14,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 15,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
      ],
    },
    {
      id: 2,
      rows: [
        {
          id: 0,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 1,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 2,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 3,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 4,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 5,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 6,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 7,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 8,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 9,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 10,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 11,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 12,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 13,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 14,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 15,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
      ],
    },
    {
      id: 3,
      rows: [
        {
          id: 0,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 1,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 2,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 3,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 4,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 5,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 6,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 7,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 8,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 9,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 10,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 11,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 12,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 13,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 14,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 15,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
      ],
    },
    {
      id: 4,
      rows: [
        {
          id: 0,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 1,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 2,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 3,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 4,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 5,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 6,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 7,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 8,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 9,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 10,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 11,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 12,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 13,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 14,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
        {
          id: 15,
          note: "F",
          octave: 5,
          instrument: 7,
          volume: 0,
          effect: "A",
          parameter: 10,
        },
      ],
    },
  ],
};

function App() {
  return (
    <div id="app">
      <div id="panel">
      </div>
      <div id="tracker" className="tracker">
        <div id="lines" className="lines">
          {[...Array(ROWS)].map((_, index) => (
            <div className="line">{index.toString(16).toUpperCase()}</div>
          ))}
        </div>
        {[...Array(CHANNELS)].map((_, index) => (
          <Channel id={index}></Channel>
        ))}
      </div>
    </div>
  );
}
function Channel(props) {
  return (
    <div id={"channel_" + props.id} className="channel">
      <div id={"name_" + props.id}>{props.id.toString(16).toUpperCase()}</div>
      <hr/>
      <div id="track_0">
        {
          tune.channels[props.id]['rows'].map((data, index) => (
              <div className="rows">
                <input className="row row-note" value={data.note + "-" + data.octave} />
                <input className="row row-instrument" value={"." + data.instrument} />
                <input className="row row-volume" value="." />
                <input className="row row-effect" value={data.effect} />
                <input className="row row-parameter" value={data.parameter} />
              </div>
          ))
        }
      </div>
    </div>
  );
}
export default App;
